---
title: "Unit 14 & Unit 15"
author: "Simi"
output: html_document
---

---
title: "AWS S3 and R"
author: "Simi Augustine"
output: html_document
---

# Loading Data From S3 Objects Using the aws.s3 package
```{r}
install.packages("ggplot2")
install.packages("aws.s3")

library(tidyverse)
library(dplyr)
library(ggplot2)
library("GGally")
library(aws.s3)

Sys.setenv("AWS_ACCESS_KEY_ID" = "AKIAYDHJABOVWCTRSW5V",
           "AWS_SECRET_ACCESS_KEY" = "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",
           "AWS_DEFAULT_REGION" = "us-east-2")


# Using aws.s3
aws.s3::bucketlist()
aws.s3::get_bucket("ddsproject1")


# read and write from ojbect

#Read in CaseStudy2-Data.csv
CaseStudy2 = s3read_using(FUN = read.csv,
                    bucket = "ddsproject1",
                    object = "CaseStudy2-data.csv")

#Read in CaseStudy2CompSet No Attrition.csv
CaseStudy2CompSetNoAttrition = s3read_using(FUN = read.csv,
                    bucket = "ddsproject1",
                    object = "CaseStudy2CompSet No Attrition.csv")

#Read in Case2PredictionsClassifyEXAMPLE.csv
Case2PredictionsClassifyEXAMPLE = s3read_using(FUN = read.csv,
                    bucket = "ddsproject1",
                    object = "Case2PredictionsClassifyEXAMPLE.csv")

ggplot(CaseStudy2, aes(x=Attrition, y=Age)) + geom_point() +
            labs(title = "Scatter Plot", x = "Attrition", y = "Age")



t.test(Score~Treatment, data = creativity)


#Write mtcars to S3
s3write_using(mtcars,FUN = write.csv,
                    bucket = "ds6306.unit13",
                    object = "mtcars.csv")


# Read in and change IRIS and then write back
library(jsonlite)
iris2 = s3read_using(FUN = fromJSON,
                    bucket = "ds6306.unit13",
                    object = "iris.json")

iris2 = iris2 %>% mutate(diff_Sep_Pet_Length = Sepal.Length - Petal.Length, diff_Sep_Pet_Width = Sepal.Width - Petal.Width)

iris2 %>% ggplot(aes(x = diff_Sep_Pet_Length, y = diff_Sep_Pet_Width, color = Species)) + geom_point() + geom_smooth(method = "lm")

s3write_using(iris2,FUN = write_json,
                    bucket = "ds6306.unit13",
                    object = "iris2.txt")

#Write a plot/chart to S3

png("irisScatter.png")

iris2 %>% ggplot(aes(x = diff_Sep_Pet_Length, y = diff_Sep_Pet_Width, color = Species)) + geom_point() + geom_smooth(method = "lm")

dev.off()

put_object("irisScatter.png", object = "irisScatter2.png", bucket = "ds6306.unit13")

```



#AcuSpike Heatmap Example!
```{r}

library(tidyverse)
library(readr)
library(aws.s3)

Sys.setenv("AWS_ACCESS_KEY_ID" = "YOURKEY",
           "AWS_SECRET_ACCESS_KEY" = "YOUR SECRET KEY",
           "AWS_DEFAULT_REGION" = "us-east-2")

jpeg("ThePlot.jpeg")
mtcars %>% ggplot(aes(x = mpg, y = cyl)) + geom_point()
dev.off()

#save the jpeg
put_object("ThePlot.jpeg", object = "ThePlot111.jpeg", bucket = "smuds6306")



# Data clean and heat map for Acuspikes 
# Data has been read into a Dataframe called "Acu"

library(ggplot2)
library(maps)
library(dplyr)
library(mapproj)

#Read in the Data from S3
Acu = s3read_using(FUN = read.csv,
                    bucket = "smuds6306",
                    object = "Acuspike Customer Data.csv") # read in company data

lookup = data.frame(abb = state.abb, State = state.name) #makes a data frame with State name and abbreviation. 
colnames(Acu)[2] = "abb" # Change Column Name
Acu2 = merge(Acu,lookup,"abb") # make one dataset with state names and abb
AcuMapData = count(Acu2,State) #count up the occurance of each state. 
#AcuMapData = AcuMapData[-c(5,9,43),] #Shows contrast between other states better
colnames(AcuMapData)[2] = "AcuSpikes" #change "n" to "Acuspikes"
AcuMapData$region <- tolower(AcuMapData$State)
AcuMapData2 = AcuMapData[-1]
states <- map_data("state")
map.df <- merge(states,AcuMapData2, by="region", all.x=T)
map.df <- map.df[order(map.df$order),]

#Generate and save the heatmap on EC2
png("AcuHeatmap.png")
ggplot(map.df, aes(x=long,y=lat,group=group))+
  geom_polygon(aes(fill=AcuSpikes))+
  geom_path()+ 
  scale_fill_gradientn(colours=rev(heat.colors(10)),na.value="grey90")+ggtitle("Acuspike Systems by State")+
coord_map()
dev.off()

#Save the heatmap to S3
put_object("AcuHeatmap.png", object = "AcuHeatmap.png", bucket = "smuds6306")

#Save the new data set used to generate the heatmap to S3
s3write_using(map.df,FUN = write.csv,
                    bucket = "ds6306.unit13",
                    object = "AcuMapData.csv")

```




